"{\
  'general':\
  {\
    'name':'hub',\
    'instance':1\
  },\
  'components':[\
    {\
     'name':'LTE',\
     'params':['hologram','','','A5']\
    },\
    {\
      'name':'LoRa',\
      'params':[255,0,23,7,500]\
    },\
    {\
      'name':'DS3231',\
      'params':'default'\
    },\
    {\
      'name':'SD',\
      'params':[true,1000,11,'hub',true]\
    },\
    {\
      'name':'GoogleSheets',\
      'params':[\
        'Goog',\
        '/macros/s/AKfycbzySpouxdaHYh6f1e7DI24i4s8XTGDe-X6d-9uaR7HVrpFNWUt7/exec',\
        '11bmZETLyFutZHwZRrpmsNFy0VrWmJ-myskjLZ6cZS-w',\
/*true to autoname tab*/        true,\
/*not used if previous param is true*/  'testTab'\
      ]\
    }\
  ]\
}"
